version: '2'

services:
  jenkins:
    restart: always
    build:
       context: ./
       dockerfile: Dockerfile
    volumes_from: 
     - container:jenkins-data
    ports:
     - "8080:8080"
     - "50000:50000"
   
